"""Gateway module for Kesoku AI Agent.

Orchestrates incoming/outgoing messages between chatbots and SQLite persistence
via DatabaseManager using a Pure Broker Pattern.
"""

import asyncio
import os
import shutil
import time
from collections.abc import AsyncGenerator, Callable
from typing import Any

from kesoku.agent.prompt import build_sys_prompt
from kesoku.constants import MessageRole, MessageStatus
from kesoku.context import KesokuContext
from kesoku.db import Message, Session
from kesoku.logger import setup_logger

logger = setup_logger(__name__)


class Listener:
    """Internal container for an active subscriber to the Gateway broker."""

    def __init__(self, filter_func: Callable[[Message], bool], maxsize: int = 1000) -> None:
        """Initialize a listener with an async queue and filter function."""
        self.queue: asyncio.Queue[Message] = asyncio.Queue(maxsize=maxsize)
        self.filter_func = filter_func


class Gateway:
    """Manages message ingestion, routing, and persistence across chatbots using a stateless broker pattern."""

    def __init__(
        self,
        context: KesokuContext | None = None,
    ) -> None:
        """Initialize the Gateway.

        Args:
            context: Runtime context container.
        """
        self.context = context or KesokuContext()
        self.workspace_config = self.context.config.workspace
        self.db = self.context.db

        self.db_path = self.workspace_config.db_path
        self._listeners: set[Listener] = set()
        self.context.sync_db.verify_db()
        self.agent: Any | None = None
        self.cron_manager: Any | None = None

    def register_agent(self, agent: Any) -> None:
        """Register an active Agent dispatcher instance.

        Args:
            agent: The active Agent instance.
        """
        self.agent = agent

    def register_cron_manager(self, cron_manager: Any) -> None:
        """Register the active CronManager instance.

        Args:
            cron_manager: The active CronManager instance.
        """
        self.cron_manager = cron_manager

    async def create_session(
        self,
        session_id: str | None = None,
        title: str = "New Session",
        system_prompt: str | None = None,
        custom_prompt: str | None = None,
        created_at: float | None = None,
        chatbot_id: str | None = None,
        channel_id: str | None = None,
        role: str | None = None,
    ) -> Session:
        """Create a new chat session record in SQLite and initialize system instructions.

        Args:
            session_id: Optional unique identifier. If None, a random 8-char hex is generated by Session model.
            title: Summary title or first message snippet for the session.
            system_prompt: Optional defining system prompt instructions (pre-built).
            custom_prompt: Optional custom instructions to include in the built system prompt.
            created_at: Optional initial creation timestamp float.
            chatbot_id: Optional chatbot platform/instance identifier.
            channel_id: Optional external channel identifier.
            role: Optional pre-resolved character persona binding.

        Returns:
            The created Session instance.
        """
        now = created_at if created_at is not None else time.time()
        sess_kwargs = {"title": title, "created_at": now, "updated_at": now}
        if session_id is not None:
            sess_kwargs["id"] = session_id
        sess = Session(**sess_kwargs)

        # Build system prompt if not provided
        if system_prompt is None:
            system_prompt = build_sys_prompt(custom_prompt=custom_prompt, session=sess, role=role)
        sess.system_prompt = system_prompt

        await self.db.create_session(sess)
        logger.debug(f"Created new chat session: {sess.id} ({title})")

        # If chatbot/channel parameters are provided, explicitly bind the active session mapping
        if chatbot_id and channel_id:
            await self.db.set_active_session_for_channel(chatbot_id, channel_id, sess.id)

        return sess

    async def post(self, message: Message) -> Message:
        """Post a message to storage and broadcast to active matching listeners.

        Args:
            message: The Message instance to post.

        Returns:
            The posted Message.
        """
        await self.db.save_message(message)
        logger.debug(f"Gateway posted message {message.id} ({message.role}:{message.sender})")

        for listener in list(self._listeners):
            if listener in self._listeners:
                if listener.filter_func(message):
                    try:
                        listener.queue.put_nowait(message)
                    except asyncio.QueueFull:
                        logger.warning(
                            f"Listener queue is full (maxsize={listener.queue.maxsize}). "
                            f"Dropping message {message.id} for this listener."
                        )

        return message

    async def listen(
        self,
        exclude_statuses: list[str] | None = None,
        exclude_roles: list[str] | None = None,
        **filters: Any,
    ) -> AsyncGenerator[Message, None]:
        """Subscribe to messages matching specified filter criteria.

        Yields messages from storage (offline recovery / initial pending) and incoming real-time posts.

        Args:
            exclude_statuses: Optional list of message lifecycle statuses to ignore.
            exclude_roles: Optional list of message roles to ignore.
            filters: Key-value attribute matches (e.g. role='user', status='pending').
        """

        def filter_func(msg: Message) -> bool:
            if exclude_statuses and msg.status in exclude_statuses:
                return False
            if exclude_roles and msg.role in exclude_roles:
                return False
            for k, v in filters.items():
                if getattr(msg, k, None) != v:
                    return False
            return True

        listener = Listener(filter_func)
        self._listeners.add(listener)
        seen_ids = set()

        # Offline recovery / initial pending fetch
        # Agent dispatcher recovers MessageStatus.PENDING_AGENT user messages,
        # while chatbot adapters recover MessageStatus.PENDING assistant responses.
        is_agent_query = filters.get("role") == MessageRole.USER
        recovery_status = MessageStatus.PENDING_AGENT if is_agent_query else MessageStatus.PENDING

        recovery_filters = {**filters}
        if "status" not in recovery_filters:
            recovery_filters["status"] = recovery_status

        pending_messages = await self.db.get_messages_by_filters(recovery_filters, None, exclude_roles)
        for msg in pending_messages:
            if msg.id not in seen_ids:
                seen_ids.add(msg.id)
                yield msg

        try:
            while True:
                msg = await listener.queue.get()
                if msg.id not in seen_ids:
                    seen_ids.add(msg.id)
                    yield msg
        finally:
            self._listeners.discard(listener)

    async def abort_session(self, session_id: str) -> None:
        """Abort any active processing for the session (e.g. if the channel is deleted).

        Args:
            session_id: Target session ID.
        """
        try:
            await self.context.active_jobs.stop_all_for_session(session_id)
        except Exception as e:
            logger.warning(f"Failed to clean up background jobs in abort_session: {e}")

        if self.agent:
            logger.info(f"Aborting active session worker for session {session_id} due to lost channel.")
            await self.agent.stop_session_worker(session_id, immediate=True)

        # Mark all outstanding (pending, processing, pending_agent) messages in this session as MessageStatus.ERROR
        history = await self.db.get_session_history(session_id, limit=0)
        for msg in history:
            if msg.status in (MessageStatus.PENDING_AGENT, MessageStatus.PROCESSING, MessageStatus.PENDING):
                await self.db.update_message_status(msg.id, MessageStatus.ERROR)

    async def delete_session(self, session_id: str) -> None:
        """Delete a session, its message history from database, and its workspace from disk.

        Args:
            session_id: The target session ID.
        """
        try:
            await self.context.active_jobs.stop_all_for_session(session_id)
        except Exception as e:
            logger.warning(f"Failed to clean up background jobs in delete_session: {e}")

        session = await self.db.get_session(session_id)
        if session:
            # Delete the staging session workspace folder from disk
            workspace_dir = os.path.join(self.workspace_config.sessions_dir, session.workspace_name)
            # Check existence asynchronously using to_thread
            if await asyncio.to_thread(os.path.exists, workspace_dir):
                try:
                    # Recursively delete directory asynchronously via to_thread
                    await asyncio.to_thread(shutil.rmtree, workspace_dir)
                    logger.debug(f"Deleted session workspace directory: {workspace_dir}")
                except Exception as e:
                    logger.warning(f"Failed to delete session workspace directory {workspace_dir}: {e}")

            # Delete the SQLite database records
            await self.db.delete_session(session_id)
            logger.info(f"Successfully deleted session {session_id} from database.")
