"""LLM backend interface and implementations for Kesoku AI Agent.

Provides an abstract base class BaseLLM and a concrete GeminiLLM implementation.
"""

import asyncio
import os
from abc import ABC, abstractmethod
from collections.abc import Callable
from typing import Any

from google import genai
from google.genai import types
from pydantic import BaseModel, Field

from kesoku.config import GeminiConfig, get_config
from kesoku.constants import (
    ROLE_ASSISTANT,
    ROLE_SYSTEM,
    ROLE_TOOL,
    ROLE_USER,
    TYPE_THOUGHT,
    TYPE_TOOL_CALL,
    TYPE_TOOL_RESULT,
)
from kesoku.db import Message
from kesoku.logger import setup_logger

logger = setup_logger(__name__)


class ToolCallRequest(BaseModel):
    """Represents a requested tool execution from the LLM."""

    name: str
    arguments: dict[str, Any]
    thought_signature: str | None = None


class LLMResponse(BaseModel):
    """Standardized response from any LLM provider."""

    content: str
    thought: str | None = None
    tool_calls: list[ToolCallRequest] = Field(default_factory=list)
    prompt_tokens: int | None = None  # Input tokens (context history, system prompt, tools schema)
    candidates_tokens: int | None = None  # Output tokens generated by the model (thoughts, text responses, tool calls)
    total_tokens: int | None = None  # Total tokens consumed in this call (prompt + candidates)


class BaseLLM(ABC):
    """Abstract base class defining the interface for LLM providers."""

    @abstractmethod
    async def generate(
        self,
        prompt: str | None = None,
        system_prompt: str | None = None,
        history: list[Message] | None = None,
        tools: list[Callable] | None = None,
    ) -> LLMResponse:
        """Generate a response from the LLM given prompt and context.

        Args:
            prompt: The latest user prompt string or None if continuation.
            system_prompt: Optional system instructions.
            history: Optional list of prior messages in the session.
            tools: Optional list of callable Python tool functions.

        Returns:
            An LLMResponse containing text and/or requested tool calls.
        """
        pass


class GeminiLLM(BaseLLM):
    """Google GenAI (Gemini) implementation of BaseLLM supporting API Key and Vertex AI."""

    def __init__(self, config: GeminiConfig | None = None) -> None:
        """Initialize the Gemini LLM client.

        Args:
            config: Configuration structure for Gemini backend.
        """
        if config is None:
            config = get_config().gemini
        self.config = config
        self.model_name = config.model_name
        logger.info(f"Using GeminiLLM backend ({self.model_name}).")

        try:
            if config.auth_mode == "vertex":
                logger.info(
                    f"Initializing Gemini client in Vertex AI mode "
                    f"(Project: {config.project_id}, Region: {config.location})"
                )
                self.client = genai.Client(
                    vertexai=True,
                    project=config.project_id,
                    location=config.location,
                )
            else:
                key = config.api_key or os.getenv("GEMINI_API_KEY")
                if not key:
                    logger.warning("GEMINI_API_KEY is not set. GeminiLLM calls may fail if not authenticated.")
                self.client = genai.Client(api_key=key)
        except ImportError:
            logger.error("google-genai package is not installed.")
            raise

    async def generate(
        self,
        prompt: str | None = None,
        system_prompt: str | None = None,
        history: list[Message] | None = None,
        tools: list[Callable] | None = None,
    ) -> LLMResponse:
        """Generate content using Google GenAI client."""
        contents: list[types.Content] = []
        if history:
            for msg in history:
                if msg.role == ROLE_SYSTEM:
                    if not system_prompt:
                        system_prompt = msg.content
                    elif msg != history[0]:
                        part = types.Part.from_text(text=f"[System Notification]\n{msg.content}")
                        if contents and contents[-1].role == "user":
                            contents[-1].parts.append(part)
                        else:
                            contents.append(types.Content(role="user", parts=[part]))
                    continue

                role = "user"
                part = None

                if msg.role == ROLE_USER:
                    role = "user"
                    part = types.Part.from_text(text=msg.content)
                elif msg.role == ROLE_ASSISTANT:
                    role = "model"
                    part = types.Part.from_text(text=msg.content)
                    if msg.type == TYPE_THOUGHT:
                        part.thought = True
                elif msg.role == ROLE_TOOL:
                    if msg.type == TYPE_TOOL_CALL:
                        role = "model"
                        tool_name = msg.metadata.get("tool_name", "unknown_tool")
                        args = msg.metadata.get("tool_arguments", {})
                        part = types.Part.from_function_call(name=tool_name, args=args)
                        ts_hex = msg.metadata.get("thought_signature")
                        if ts_hex:
                            part.thought_signature = bytes.fromhex(ts_hex)
                    elif msg.type == TYPE_TOOL_RESULT:
                        role = "tool"
                        tool_name = msg.metadata.get("tool_name", "unknown_tool")
                        if "tool_error" in msg.metadata:
                            res_dict = {"error": msg.metadata["tool_error"]}
                        else:
                            res_dict = {"result": msg.metadata.get("tool_result", msg.content)}
                        part = types.Part.from_function_response(name=tool_name, response=res_dict)

                if part:
                    if contents and contents[-1].role == role:
                        contents[-1].parts.append(part)
                    else:
                        contents.append(types.Content(role=role, parts=[part]))

        if prompt:
            part = types.Part.from_text(text=prompt)
            if contents and contents[-1].role == "user":
                contents[-1].parts.append(part)
            else:
                contents.append(types.Content(role="user", parts=[part]))

        config = types.GenerateContentConfig()
        if system_prompt:
            config.system_instruction = system_prompt
        if tools:
            config.tools = tools  # type: ignore
            config.automatic_function_calling = types.AutomaticFunctionCallingConfig(disable=True)
        if self.config.thinking_level is not None:
            config.thinking_config = types.ThinkingConfig(
                thinking_level=self.config.thinking_level,
                include_thoughts=True,
            )

        def _call() -> Any:
            if self.config.auth_mode == "vertex":
                client = genai.Client(
                    vertexai=True,
                    project=self.config.project_id,
                    location=self.config.location,
                )
            else:
                key = self.config.api_key or os.getenv("GEMINI_API_KEY")
                client = genai.Client(api_key=key)

            return client.models.generate_content(
                model=self.model_name,
                contents=contents,
                config=config,
            )

        try:
            res = await asyncio.to_thread(_call)
            tool_calls = []
            text_parts = []
            thought_parts = []

            if res.parts:
                for part in res.parts:
                    if isinstance(part.text, str):
                        if part.thought:
                            thought_parts.append(part.text)
                        else:
                            text_parts.append(part.text)
                    if part.function_call:
                        call = part.function_call
                        args_dict = dict(call.args) if call.args else {}
                        ts = part.thought_signature.hex() if part.thought_signature else None
                        tool_calls.append(ToolCallRequest(name=call.name, arguments=args_dict, thought_signature=ts))

            text_content = "".join(text_parts)
            thought_content = "".join(thought_parts) if thought_parts else None

            prompt_tokens = None
            candidates_tokens = None
            total_tokens = None
            if getattr(res, "usage_metadata", None):
                prompt_tokens = res.usage_metadata.prompt_token_count
                candidates_tokens = res.usage_metadata.candidates_token_count
                total_tokens = res.usage_metadata.total_token_count

            return LLMResponse(
                content=text_content,
                thought=thought_content,
                tool_calls=tool_calls,
                prompt_tokens=prompt_tokens,
                candidates_tokens=candidates_tokens,
                total_tokens=total_tokens,
            )

        except Exception as e:
            logger.error(f"GeminiLLM generation failed: {e}")
            raise


class MockLLM(BaseLLM):
    """Mock LLM implementation for unit testing and local verification."""

    def __init__(
        self, mock_response: str = "Hello! I am Kesoku Agent.", mock_tools: list[ToolCallRequest] | None = None
    ) -> None:
        """Initialize MockLLM with canned responses."""
        self.mock_response = mock_response
        self.mock_tools = mock_tools or []

    async def generate(
        self,
        prompt: str | None = None,
        system_prompt: str | None = None,
        history: list[Message] | None = None,
        tools: list[Callable] | None = None,
    ) -> LLMResponse:
        """Return canned mock response."""
        logger.debug(f"MockLLM received prompt: {prompt}, history count: {len(history or [])}")
        prompt_str = prompt or (history[-1].content if history else "")
        if history and history[-1].role == "tool" and history[-1].type == "tool_result":
            return LLMResponse(content="The calculation result is 35.", tool_calls=[])
        if "calculate" in prompt_str.lower() or "+" in prompt_str:
            return LLMResponse(
                content="Let me calculate that.",
                tool_calls=[ToolCallRequest(name="calculator", arguments={"expression": "25 + 10"})],
            )
        return LLMResponse(content=self.mock_response, tool_calls=self.mock_tools)


def get_llm(provider: str | None = None) -> BaseLLM:
    """Get an LLM instance based on config or specified provider.

    Args:
        provider: Optional provider name ('gemini' or 'mock'). If None, uses agent.llm from config.

    Returns:
        An instance of BaseLLM (GeminiLLM or MockLLM).

    Raises:
        ValueError: If an unsupported LLM provider is specified.
    """
    if provider is None:
        provider = get_config().agent.llm

    provider_lower = provider.lower()
    if provider_lower == "gemini":
        return GeminiLLM()
    elif provider_lower == "mock":
        return MockLLM()
    else:
        raise ValueError(f"Unsupported LLM provider: {provider}")
