"""LLM backend interface and implementations for Kesoku AI Agent.

Provides an abstract base class BaseLLM and a concrete GeminiLLM implementation.
"""

import asyncio
import base64
import inspect
import io
import os
import re
import typing
from abc import ABC
from collections.abc import Callable
from typing import Any, Literal

from anthropic import AnthropicVertex
from google import genai
from google.genai import _transformers, types
from PIL import Image
from pydantic import BaseModel, Field

from kesoku.config import ClaudeConfig, GeminiConfig, KesokuConfig, get_config
from kesoku.constants import MessageRole, MessageType
from kesoku.db import Message
from kesoku.logger import setup_logger

logger = setup_logger(__name__)


class ToolCallRequest(BaseModel):
    """Represents a requested tool execution from the LLM."""

    name: str
    arguments: dict[str, Any]
    thought_signature: str | None = None
    tool_call_id: str | None = None


class LLMResponse(BaseModel):
    """Standardized response from any LLM provider."""

    content: str
    thought: str | None = None
    tool_calls: list[ToolCallRequest] = Field(default_factory=list)
    prompt_tokens: int | None = None  # Input tokens (context history, system prompt, tools schema)
    candidates_tokens: int | None = None  # Output tokens generated by the model (thoughts, text responses, tool calls)
    total_tokens: int | None = None  # Total tokens consumed in this call (prompt + candidates)
    cached_tokens: int | None = None  # Cached input tokens
    raw_response: str | None = None  # Raw model response representation


class TextBlock(BaseModel):
    """Represents a standard text segment in the conversational turn."""

    type: Literal["text"] = "text"
    text: str


class ThoughtBlock(BaseModel):
    """Represents a structured thought process / reasoning segment."""

    type: Literal["thought"] = "thought"
    text: str


class ImageBlock(BaseModel):
    """Represents an image attachment containing raw bytes."""

    type: Literal["image"] = "image"
    media_type: str
    data: bytes


class DocumentBlock(BaseModel):
    """Represents a document attachment (e.g., PDF) containing raw bytes."""

    type: Literal["document"] = "document"
    media_type: str
    data: bytes


class ToolCallBlock(BaseModel):
    """Represents a requested tool call from the assistant."""

    type: Literal["tool_call"] = "tool_call"
    name: str
    arguments: dict[str, Any]
    tool_call_id: str
    thought_signature: str | None = None


class ToolResultBlock(BaseModel):
    """Represents the output result of an executed tool call."""

    type: Literal["tool_result"] = "tool_result"
    name: str
    tool_call_id: str
    result: str
    is_error: bool = False


LLMBlock = TextBlock | ThoughtBlock | ImageBlock | DocumentBlock | ToolCallBlock | ToolResultBlock


class LLMTurn(BaseModel):
    """Represents a single conversational turn with one role."""

    role: MessageRole
    blocks: list[LLMBlock] = Field(default_factory=list)


def _resize_and_compress_image(file_bytes: bytes, max_size: int = 1024) -> tuple[bytes, str]:
    """Resize image to have max_size as maximum dimension and compress to WebP.

    Args:
        file_bytes: Original image file bytes.
        max_size: Maximum allowed width or height.

    Returns:
        Tuple of (processed_image_bytes, mime_type).
    """
    try:
        img = Image.open(io.BytesIO(file_bytes))

        # Convert palette or other modes to RGB/RGBA to support WebP format
        if img.mode not in ("RGB", "RGBA"):
            img = img.convert("RGBA")

        width, height = img.size
        if width > max_size or height > max_size:
            if width > height:
                new_width = max_size
                new_height = int(height * (max_size / width))
            else:
                new_height = max_size
                new_width = int(width * (max_size / height))

            img = img.resize((new_width, new_height), Image.Resampling.LANCZOS)
            logger.info(f"Resized image from {width}x{height} to {new_width}x{new_height}")

        out_io = io.BytesIO()
        img.save(out_io, format="WEBP", quality=80)
        compressed_bytes = out_io.getvalue()

        # Only use compressed bytes if it actually saves space
        if len(compressed_bytes) < len(file_bytes):
            logger.info(f"Compressed image using WebP: {len(file_bytes)} -> {len(compressed_bytes)} bytes")
            return compressed_bytes, "image/webp"

        return file_bytes, "image/webp"
    except Exception as e:
        logger.error(f"Failed to resize and compress image: {e}")
        return file_bytes, "image/webp"


def _load_attachments(attachments: list[dict[str, Any]]) -> list[ImageBlock | DocumentBlock]:
    """Load local attachments from paths and wrap them in ImageBlock or DocumentBlock.

    Args:
        attachments: List of dictionaries containing 'path' and 'mime_type'.

    Returns:
        List of loaded blocks.
    """
    blocks: list[ImageBlock | DocumentBlock] = []
    for att in attachments:
        path = att.get("path")
        mime_type = att.get("mime_type", "application/octet-stream")
        if path and os.path.exists(path):
            try:
                with open(path, "rb") as f:
                    file_bytes = f.read()
                corrected_mime = mime_type
                if mime_type.startswith("image/"):
                    corrected_mime = _detect_image_mime_type(file_bytes, fallback_mime=mime_type)
                    # Resize and compress image using WebP
                    processed_bytes, processed_mime = _resize_and_compress_image(file_bytes, max_size=1024)
                    if processed_bytes != file_bytes:
                        corrected_mime = processed_mime
                        file_bytes = processed_bytes
                    blocks.append(ImageBlock(media_type=corrected_mime, data=file_bytes))
                    logger.info(f"Loaded native image part: {path} ({corrected_mime})")
                elif mime_type == "application/pdf":
                    blocks.append(DocumentBlock(media_type="application/pdf", data=file_bytes))
                    logger.info(f"Loaded native document part: {path} ({mime_type})")
                else:
                    logger.warning(f"Unsupported attachment type: {mime_type}")
            except Exception as ex:
                logger.error(f"Failed to load attachment {path}: {ex}")
    return blocks


def history_to_turns(
    history: list[Message] | None,
    prompt: str | None = None,
    system_prompt: str | None = None,
) -> tuple[list[LLMTurn], str | None]:
    """Convert flat database Message history + latest prompt to structured LLMTurn IR.

    Also extracts and resolves the initial system prompt.

    Args:
        history: Sequential list of database Messages.
        prompt: Optional latest user prompt string.
        system_prompt: Optional system prompt string override.

    Returns:
        Tuple of (list of LLMTurns, resolved system prompt).
    """
    turns: list[LLMTurn] = []
    resolved_system_prompt = system_prompt

    def add_blocks(role: MessageRole, blocks: list[LLMBlock]) -> None:
        """Append blocks to the last turn if roles match; otherwise start a new turn."""
        if not blocks:
            return
        if turns and turns[-1].role == role:
            turns[-1].blocks.extend(blocks)
        else:
            turns.append(LLMTurn(role=role, blocks=blocks))

    # Pre-pass: Map tool call message IDs to tool_call_ids
    tool_call_ids = {}
    if history:
        for msg in history:
            if msg.role == MessageRole.TOOL and msg.type == MessageType.TOOL_CALL:
                tool_call_id = msg.metadata.get("tool_call_id") or msg.id
                tool_call_ids[msg.id] = tool_call_id

    if history:
        for msg in history:
            if msg.role == MessageRole.SYSTEM:
                if not resolved_system_prompt:
                    resolved_system_prompt = msg.content
                elif msg != history[0]:
                    notification = f"[System Notification]\n{msg.content}"
                    add_blocks(MessageRole.USER, [TextBlock(text=notification)])
                continue

            if msg.role == MessageRole.USER:
                blocks: list[LLMBlock] = [TextBlock(text=msg.content)]
                attachments = msg.metadata.get("attachments", [])
                if attachments:
                    blocks.extend(_load_attachments(attachments))
                add_blocks(MessageRole.USER, blocks)

            elif msg.role == MessageRole.ASSISTANT:
                if msg.type == MessageType.THOUGHT:
                    add_blocks(MessageRole.ASSISTANT, [ThoughtBlock(text=msg.content)])
                else:
                    add_blocks(MessageRole.ASSISTANT, [TextBlock(text=msg.content)])

            elif msg.role == MessageRole.TOOL:
                if msg.type == MessageType.TOOL_CALL:
                    tool_name = msg.metadata.get("tool_name", "unknown_tool")
                    args = msg.metadata.get("tool_arguments", {})
                    tool_call_id = msg.metadata.get("tool_call_id") or msg.id
                    ts_hex = msg.metadata.get("thought_signature")
                    add_blocks(
                        MessageRole.ASSISTANT,
                        [
                            ToolCallBlock(
                                name=tool_name,
                                arguments=args,
                                tool_call_id=tool_call_id,
                                thought_signature=ts_hex,
                            )
                        ],
                    )
                elif msg.type == MessageType.TOOL_RESULT:
                    tool_name = msg.metadata.get("tool_name", "unknown_tool")
                    if "tool_error" in msg.metadata:
                        res_str = f"Error: {msg.metadata['tool_error']}"
                        is_error = True
                    else:
                        res_str = msg.metadata.get("tool_result", msg.content)
                        is_error = False

                    tool_call_id = msg.metadata.get("tool_call_id")
                    if not tool_call_id:
                        tool_call_id = tool_call_ids.get(msg.parent_id) or msg.parent_id or msg.id or "unknown"

                    add_blocks(
                        MessageRole.TOOL,
                        [
                            ToolResultBlock(
                                name=tool_name,
                                tool_call_id=tool_call_id,
                                result=res_str,
                                is_error=is_error,
                            )
                        ],
                    )

    if prompt:
        add_blocks(MessageRole.USER, [TextBlock(text=prompt)])

    return turns, resolved_system_prompt


def function_to_anthropic_tool(func: Callable) -> dict[str, Any]:
    """Convert a Python function with type hints and docstrings to an Anthropic tool schema.

    Args:
        func: The Python callable function to convert.

    Returns:
        A dict matching the Anthropic tool schema format.
    """
    sig = inspect.signature(func)

    # Get description from docstring
    doc = inspect.getdoc(func) or ""
    # Use the first line of docstring as the summary description
    description = doc.split("\n\n")[0] if doc else f"Run the {func.__name__} function"

    properties = {}
    required = []

    # Map python type annotation to JSON schema types
    type_map = {
        str: "string",
        int: "integer",
        float: "number",
        bool: "boolean",
        dict: "object",
        list: "array",
    }

    for param_name, param in sig.parameters.items():
        if param_name == "context":
            continue  # Skip context parameter which is framework internal

        # Determine type
        param_type = "string"  # default fallback
        annotation = param.annotation

        # Handle Optional or Union types (like str | None or typing.Optional)
        origin = typing.get_origin(annotation)
        if origin is typing.Union or str(origin) == "<class 'union'>":
            args = typing.get_args(annotation)
            non_none_args = [a for a in args if a is not type(None)]
            if non_none_args:
                annotation = non_none_args[0]

        if annotation in type_map:
            param_type = type_map[annotation]

        # Handle default value and required list
        param_prop = {"type": param_type}

        # Search docstring for parameter description: "param_name: description"
        param_desc = f"The {param_name} argument"
        if doc:
            pattern = rf"(?:Args:|Parameters:).*?{param_name}\s*:\s*(.*?)(?:\n\s*\w+\s*:|\n\n|\Z)"
            match = re.search(pattern, doc, re.DOTALL | re.IGNORECASE)
            if match:
                param_desc = match.group(1).strip().replace("\n", " ")

        param_prop["description"] = param_desc
        properties[param_name] = param_prop

        if param.default is inspect.Parameter.empty:
            required.append(param_name)

    return {
        "name": func.__name__,
        "description": description,
        "input_schema": {
            "type": "object",
            "properties": properties,
            "required": required,
        },
    }


def _detect_image_mime_type(file_bytes: bytes, fallback_mime: str = "image/jpeg") -> str:
    """Detect image mime type from magic bytes.

    Returns:
        The detected mime_type string (e.g., 'image/png', 'image/jpeg').
    """
    if file_bytes.startswith(b"\x89PNG\r\n\x1a\n"):
        return "image/png"
    if file_bytes.startswith(b"\xff\xd8\xff"):
        return "image/jpeg"
    if file_bytes.startswith(b"GIF87a") or file_bytes.startswith(b"GIF89a"):
        return "image/gif"
    if file_bytes.startswith(b"RIFF") and len(file_bytes) >= 12 and file_bytes[8:12] == b"WEBP":
        return "image/webp"
    return fallback_mime


class BaseLLM(ABC):
    """Abstract base class defining the interface for LLM providers."""

    context_window_limit: int = 1048576  # Default context window limit (1M tokens)


    async def generate(
        self,
        prompt: str | None = None,
        system_prompt: str | None = None,
        history: list[Message] | None = None,
        tools: list[Callable] | None = None,
        cached_content: str | None = None,
    ) -> LLMResponse:
        """Generate a response from the LLM given prompt and context.

        Args:
            prompt: The latest user prompt string or None if continuation.
            system_prompt: Optional system instructions.
            history: Optional list of prior messages in the session.
            tools: Optional list of callable Python tool functions.
            cached_content: Optional identifier for cached context content.

        Returns:
            An LLMResponse containing text and/or requested tool calls.
        """
        turns, resolved_system_prompt = history_to_turns(history, prompt, system_prompt)
        native_input = self._build_native_input(
            turns=turns,
            system_prompt=resolved_system_prompt,
            tools=tools,
            cached_content=cached_content,
        )
        raw_res = await self._call_llm(native_input)
        return self._parse_native_response(raw_res)

    def _build_native_input(
        self,
        turns: list[LLMTurn],
        system_prompt: str | None,
        tools: list[Callable] | None,
        cached_content: str | None = None,
    ) -> Any:
        """Translate provider-neutral LLMTurns and tools into provider-native input structures."""
        raise NotImplementedError()

    async def _call_llm(self, native_input: Any) -> Any:
        """Call the underlying LLM client with the native input structures."""
        raise NotImplementedError()

    def _parse_native_response(self, raw_response: Any) -> LLMResponse:
        """Translate the provider-native response into a standardized LLMResponse."""
        raise NotImplementedError()

    async def create_cache(
        self,
        contents: list[Message],
        system_prompt: str | None = None,
        tools: list[Callable] | None = None,
        display_name: str | None = None,
        ttl_seconds: int = 300,
    ) -> str | None:
        """Create an explicit context cache resource and return its identifier.

        Args:
            contents: Static message history prefix list to cache.
            system_prompt: Optional system instruction prompt to cache.
            tools: Optional list of callables to cache.
            display_name: Optional human-readable display label.
            ttl_seconds: Cache Time-to-Live in seconds.

        Returns:
            A string name identifier of the cache resource if supported/created, else None.
        """
        return None

    async def delete_cache(self, cache_name: str) -> None:
        """Delete a created context cache resource if supported.

        Args:
            cache_name: Resource identifier name of the cache to delete.
        """
        pass


    def count_tokens(
        self,
        prompt: str | None = None,
        system_prompt: str | None = None,
        history: list[Message] | None = None,
        tools: list[Callable] | None = None,
    ) -> int:
        """Estimate or count the total input tokens for a generation payload."""
        return self.estimate_tokens_fallback(prompt, system_prompt, history)

    def estimate_tokens_fallback(
        self,
        prompt: str | None = None,
        system_prompt: str | None = None,
        history: list[Message] | None = None,
    ) -> int:
        """Fallback character-based token estimation (roughly 4 characters per token)."""
        total_chars = 0
        if prompt:
            total_chars += len(prompt)
        if system_prompt:
            total_chars += len(system_prompt)
        if history:
            for m in history:
                total_chars += len(m.content)
        return max(1, total_chars // 4)


class GeminiLLM(BaseLLM):
    """Google GenAI (Gemini) implementation of BaseLLM supporting API Key and Vertex AI."""

    def __init__(self, config: GeminiConfig | None = None) -> None:
        """Initialize the Gemini LLM client.

        Args:
            config: Configuration structure for Gemini backend.
        """
        if config is None:
            config = get_config().gemini
        self.config = config
        self.model_name = config.model_name
        self.context_window_limit = 1048576  # 1M tokens context limit for Gemini Flash
        logger.info(f"Using GeminiLLM backend ({self.model_name}).")

        try:
            if config.auth_mode == "vertex":
                logger.info(
                    f"Initializing Gemini client in Vertex AI mode "
                    f"(Project: {config.project_id}, Region: {config.location})"
                )
                self.client = genai.Client(
                    vertexai=True,
                    project=config.project_id,
                    location=config.location,
                )
            else:
                key = config.api_key or os.getenv("GEMINI_API_KEY")
                if not key:
                    logger.warning("GEMINI_API_KEY is not set. GeminiLLM calls may fail if not authenticated.")
                self.client = genai.Client(api_key=key)
        except ImportError:
            logger.error("google-genai package is not installed.")
            raise

    def _build_native_input(
        self,
        turns: list[LLMTurn],
        system_prompt: str | None,
        tools: list[Callable] | None,
        cached_content: str | None = None,
    ) -> dict[str, Any]:
        contents: list[types.Content] = []
        for turn in turns:
            role = "model" if turn.role == "assistant" else turn.role
            parts = []
            for block in turn.blocks:
                if isinstance(block, TextBlock):
                    parts.append(types.Part.from_text(text=block.text))
                elif isinstance(block, ThoughtBlock):
                    part = types.Part.from_text(text=block.text)
                    part.thought = True
                    parts.append(part)
                elif isinstance(block, ImageBlock):
                    parts.append(types.Part.from_bytes(data=block.data, mime_type=block.media_type))
                elif isinstance(block, DocumentBlock):
                    parts.append(types.Part.from_bytes(data=block.data, mime_type=block.media_type))
                elif isinstance(block, ToolCallBlock):
                    part = types.Part.from_function_call(name=block.name, args=block.arguments)
                    if block.thought_signature:
                        part.thought_signature = bytes.fromhex(block.thought_signature)
                    parts.append(part)
                elif isinstance(block, ToolResultBlock):
                    res_dict = {"error": block.result} if block.is_error else {"result": block.result}
                    part = types.Part.from_function_response(name=block.name, response=res_dict)
                    parts.append(part)

            if parts:
                if contents and contents[-1].role == role:
                    contents[-1].parts.extend(parts)
                else:
                    contents.append(types.Content(role=role, parts=parts))

        config = types.GenerateContentConfig()
        if system_prompt:
            config.system_instruction = system_prompt
        if cached_content:
            config.cached_content = cached_content
        if tools:
            config.tools = tools  # type: ignore
            config.automatic_function_calling = types.AutomaticFunctionCallingConfig(disable=True)
        if self.config.thinking_level is not None:
            config.thinking_config = types.ThinkingConfig(
                thinking_level=self.config.thinking_level,
                include_thoughts=True,
            )

        return {"contents": contents, "config": config}

    async def _call_llm(self, native_input: dict[str, Any]) -> Any:
        def _call() -> Any:
            if self.config.auth_mode == "vertex":
                client = genai.Client(
                    vertexai=True,
                    project=self.config.project_id,
                    location=self.config.location,
                )
            else:
                key = self.config.api_key or os.getenv("GEMINI_API_KEY")
                client = genai.Client(api_key=key)

            logger.info(f"GeminiLLM raw request config: {native_input['config']}")
            return client.models.generate_content(
                model=self.model_name,
                contents=native_input["contents"],
                config=native_input["config"],
            )

        try:
            return await asyncio.to_thread(_call)
        except Exception as e:
            logger.error(f"GeminiLLM generation failed: {e}")
            raise

    async def create_cache(
        self,
        contents: list[Message],
        system_prompt: str | None = None,
        tools: list[Callable] | None = None,
        display_name: str | None = None,
        ttl_seconds: int = 300,
    ) -> str | None:
        """Create an explicit context cache for Gemini.

        Args:
            contents: List of prior history messages to cache.
            system_prompt: Optional system instruction prompt to cache.
            tools: Optional list of callables to cache.
            display_name: Optional human-readable display name.
            ttl_seconds: Time-to-Live duration in seconds.

        Returns:
            The resource name string of the created cache, or None if failed.
        """
        turns, resolved_system_prompt = history_to_turns(contents, None, system_prompt)
        native_input = self._build_native_input(turns, resolved_system_prompt, None)
        native_contents = native_input["contents"]

        def _create() -> Any:
            if self.config.auth_mode == "vertex":
                client = genai.Client(
                    vertexai=True,
                    project=self.config.project_id,
                    location=self.config.location,
                )
            else:
                key = self.config.api_key or os.getenv("GEMINI_API_KEY")
                client = genai.Client(api_key=key)

            native_tools = _transformers.t_tools(client._api_client, tools) if tools else None

            return client.caches.create(
                model=self.model_name,
                config=types.CreateCachedContentConfig(
                    display_name=display_name or "kesoku_session_cache",
                    contents=native_contents,
                    system_instruction=resolved_system_prompt,
                    tools=native_tools,
                    ttl=f"{ttl_seconds}s",
                )
            )

        try:
            cache = await asyncio.to_thread(_create)
            logger.info(f"Created Gemini context cache: {cache.name}")
            return cache.name
        except Exception as e:
            logger.warning(f"Failed to create Gemini context cache: {e}")
            return None

    async def delete_cache(self, cache_name: str) -> None:
        """Delete a created context cache resource.

        Args:
            cache_name: Resource identifier name of the cache to delete.
        """
        def _delete() -> None:
            if self.config.auth_mode == "vertex":
                client = genai.Client(
                    vertexai=True,
                    project=self.config.project_id,
                    location=self.config.location,
                )
            else:
                key = self.config.api_key or os.getenv("GEMINI_API_KEY")
                client = genai.Client(api_key=key)

            client.caches.delete(name=cache_name)

        try:
            await asyncio.to_thread(_delete)
            logger.info(f"Deleted Gemini context cache: {cache_name}")
        except Exception as e:
            logger.warning(f"Failed to delete Gemini context cache {cache_name}: {e}")


    def _parse_native_response(self, raw_response: Any) -> LLMResponse:
        tool_calls = []
        text_parts = []
        thought_parts = []

        if raw_response.parts:
            for part in raw_response.parts:
                if isinstance(part.text, str):
                    if part.thought:
                        thought_parts.append(part.text)
                    else:
                        text_parts.append(part.text)
                if part.function_call:
                    call = part.function_call
                    args_dict = dict(call.args) if call.args else {}
                    ts = part.thought_signature.hex() if part.thought_signature else None
                    tool_calls.append(ToolCallRequest(name=call.name, arguments=args_dict, thought_signature=ts))

        text_content = "".join(text_parts)
        thought_content = "".join(thought_parts) if thought_parts else None

        prompt_tokens = None
        candidates_tokens = None
        total_tokens = None
        cached_tokens = None
        if getattr(raw_response, "usage_metadata", None):
            prompt_tokens = raw_response.usage_metadata.prompt_token_count
            candidates_tokens = raw_response.usage_metadata.candidates_token_count
            total_tokens = raw_response.usage_metadata.total_token_count
            cached_tokens = getattr(raw_response.usage_metadata, "cached_content_token_count", None)

        return LLMResponse(
            content=text_content,
            thought=thought_content,
            tool_calls=tool_calls,
            prompt_tokens=prompt_tokens,
            candidates_tokens=candidates_tokens,
            total_tokens=total_tokens,
            cached_tokens=cached_tokens,
        )

    def count_tokens(
        self,
        prompt: str | None = None,
        system_prompt: str | None = None,
        history: list[Message] | None = None,
        tools: list[Callable] | None = None,
    ) -> int:
        """Count exact input tokens of the context payload using the Gemini API."""
        try:
            turns, resolved_system_prompt = history_to_turns(history, prompt, system_prompt)
            native_input = self._build_native_input(turns, resolved_system_prompt, tools)

            if not native_input.get("contents"):
                return self.estimate_tokens_fallback(prompt, resolved_system_prompt or system_prompt, history)

            count_config = types.CountTokensConfig()
            if resolved_system_prompt:
                count_config.system_instruction = resolved_system_prompt

            res = self.client.models.count_tokens(
                model=self.model_name,
                contents=native_input["contents"],
                config=count_config,
            )
            return res.total_tokens
        except Exception as e:
            logger.warning(f"Failed to count tokens via Gemini API: {e}. Falling back to estimation.")
            return self.estimate_tokens_fallback(prompt, resolved_system_prompt or system_prompt, history)


class ClaudeLLM(BaseLLM):
    """Anthropic Claude implementation of BaseLLM supporting Vertex AI."""

    def __init__(self, config: ClaudeConfig | None = None) -> None:
        """Initialize the Claude LLM client.

        Args:
            config: Configuration structure for Claude backend.
        """
        if config is None:
            config = get_config().claude
        self.config = config
        self.model_name = config.model_name
        self.context_window_limit = 200000  # 200K tokens context limit for Claude
        logger.info(f"Using ClaudeLLM backend ({self.model_name}).")

        logger.info(
            f"Initializing Claude client in Vertex AI mode (Project: {config.project_id}, Region: {config.location})"
        )
        self.client = AnthropicVertex(
            project_id=config.project_id,
            region=config.location,
        )

    def _build_native_input(
        self,
        turns: list[LLMTurn],
        system_prompt: str | None,
        tools: list[Callable] | None,
        cached_content: str | None = None,
    ) -> dict[str, Any]:
        messages = []
        anthropic_tools = []
        if tools:
            for t in tools:
                anthropic_tools.append(function_to_anthropic_tool(t))

        for turn in turns:
            role = "user" if turn.role == "tool" else turn.role
            blocks = []
            for block in turn.blocks:
                if isinstance(block, TextBlock):
                    blocks.append({"type": "text", "text": block.text})
                elif isinstance(block, ThoughtBlock):
                    blocks.append({"type": "text", "text": f"<thought>\n{block.text}\n</thought>"})
                elif isinstance(block, ImageBlock):
                    data_b64 = base64.b64encode(block.data).decode("utf-8")
                    blocks.append(
                        {
                            "type": "image",
                            "source": {
                                "type": "base64",
                                "media_type": block.media_type,
                                "data": data_b64,
                            },
                        }
                    )
                elif isinstance(block, DocumentBlock):
                    data_b64 = base64.b64encode(block.data).decode("utf-8")
                    blocks.append(
                        {
                            "type": "document",
                            "source": {
                                "type": "base64",
                                "media_type": "application/pdf",
                                "data": data_b64,
                            },
                        }
                    )
                elif isinstance(block, ToolCallBlock):
                    tool_call_id = block.tool_call_id
                    if not tool_call_id.startswith("toolu_"):
                        tool_call_id = f"toolu_{tool_call_id}"
                    blocks.append(
                        {
                            "type": "tool_use",
                            "id": tool_call_id,
                            "name": block.name,
                            "input": block.arguments,
                        }
                    )
                elif isinstance(block, ToolResultBlock):
                    tool_call_id = block.tool_call_id
                    if not tool_call_id.startswith("toolu_"):
                        tool_call_id = f"toolu_{tool_call_id}"
                    tc_block = {
                        "type": "tool_result",
                        "tool_use_id": tool_call_id,
                        "content": block.result,
                    }
                    if block.is_error:
                        tc_block["is_error"] = True
                    blocks.append(tc_block)

            if blocks:
                if messages and messages[-1]["role"] == role:
                    messages[-1]["content"].extend(blocks)
                else:
                    messages.append({"role": role, "content": blocks})

        if not messages:
            messages = [{"role": "user", "content": [{"type": "text", "text": "Hello"}]}]

        if messages[0]["role"] != "user":
            messages.insert(0, {"role": "user", "content": [{"type": "text", "text": "Hello"}]})

        final_messages = []
        for m in messages:
            if final_messages and final_messages[-1]["role"] == m["role"]:
                final_messages[-1]["content"].extend(m["content"])
            else:
                final_messages.append(m)

        kwargs = {
            "model": self.model_name,
            "messages": final_messages,
            "max_tokens": 4096,
        }
        if system_prompt:
            kwargs["system"] = system_prompt
        if anthropic_tools:
            kwargs["tools"] = anthropic_tools

        return kwargs

    async def _call_llm(self, native_input: dict[str, Any]) -> Any:
        def _call() -> Any:
            return self.client.messages.create(**native_input)

        try:
            return await asyncio.to_thread(_call)
        except Exception as e:
            logger.error(f"ClaudeLLM generation failed: {e}")
            raise

    def _parse_native_response(self, raw_response: Any) -> LLMResponse:
        tool_calls = []
        text_parts = []
        thought_parts = []

        if raw_response.content:
            for block in raw_response.content:
                if block.type == "text":
                    text = block.text
                    thought_match = re.search(r"<thought>(.*?)</thought>", text, re.DOTALL)
                    if thought_match:
                        thought_parts.append(thought_match.group(1).strip())
                        text = re.sub(r"<thought>.*?</thought>", "", text, flags=re.DOTALL).strip()
                    text_parts.append(text)
                elif block.type == "tool_use":
                    tool_calls.append(
                        ToolCallRequest(
                            name=block.name,
                            arguments=dict(block.input) if block.input else {},
                            thought_signature=None,
                            tool_call_id=block.id,
                        )
                    )

        text_content = "\n".join(text_parts).strip()
        thought_content = "\n".join(thought_parts).strip() if thought_parts else None

        prompt_tokens = None
        candidates_tokens = None
        total_tokens = None
        cached_tokens = None
        if getattr(raw_response, "usage", None):
            prompt_tokens = raw_response.usage.input_tokens
            candidates_tokens = raw_response.usage.output_tokens
            total_tokens = prompt_tokens + candidates_tokens
            cached_tokens = getattr(raw_response.usage, "cache_read_input_tokens", None)

        raw_json = None
        try:
            if "Mock" in type(raw_response).__name__:
                raw_json = str(raw_response)
            elif hasattr(raw_response, "to_json"):
                val = raw_response.to_json()
                raw_json = val if isinstance(val, str) else str(val)
            elif hasattr(raw_response, "model_dump_json"):
                val = raw_response.model_dump_json()
                raw_json = val if isinstance(val, str) else str(val)
            else:
                raw_json = str(raw_response)
        except Exception as se:
            raw_json = f"Failed to serialize: {se}\nRaw: {repr(raw_response)}"

        return LLMResponse(
            content=text_content,
            thought=thought_content,
            tool_calls=tool_calls,
            prompt_tokens=prompt_tokens,
            candidates_tokens=candidates_tokens,
            total_tokens=total_tokens,
            cached_tokens=cached_tokens,
            raw_response=raw_json,
        )


class MockLLM(BaseLLM):
    """Mock LLM implementation for unit testing and local verification."""

    def __init__(
        self,
        responses: list[LLMResponse] | None = None,
        mock_response: str = "Hello! I am Kesoku Agent.",
        mock_tools: list[ToolCallRequest] | None = None,
    ) -> None:
        """Initialize MockLLM with canned responses."""
        self.responses = responses
        self._current_response_idx = 0
        self.mock_response = mock_response
        self.mock_tools = mock_tools or []
        self._returned_tools = False

    async def generate(
        self,
        prompt: str | None = None,
        system_prompt: str | None = None,
        history: list[Message] | None = None,
        tools: list[Callable] | None = None,
        cached_content: str | None = None,
    ) -> LLMResponse:
        """Return canned mock response."""
        logger.debug(
            f"MockLLM received prompt: {prompt}, history count: {len(history or [])}, "
            f"cached_content: {cached_content}"
        )
        if self.responses is not None:
            if self._current_response_idx < len(self.responses):
                res = self.responses[self._current_response_idx]
                self._current_response_idx += 1
                return res
            return LLMResponse(content="No more mocked responses available.", tool_calls=[])

        if self.mock_tools and not self._returned_tools:
            self._returned_tools = True
            return LLMResponse(content=self.mock_response, tool_calls=self.mock_tools)

        return LLMResponse(content=self.mock_response, tool_calls=[])


def get_llm(provider: str | None = None, config: KesokuConfig | None = None) -> BaseLLM:
    """Get an LLM instance based on config or specified provider.

    Args:
        provider: Optional provider name ('gemini', 'claude', or 'mock'). If None, uses agent.llm from config.
        config: Optional configuration container. If None, uses get_config().

    Returns:
        An instance of BaseLLM (GeminiLLM, ClaudeLLM, or MockLLM).

    Raises:
        ValueError: If an unsupported LLM provider is specified.
    """
    if config is None:
        config = get_config()
    if provider is None:
        provider = config.agent.llm

    provider_lower = provider.lower()
    if provider_lower == "gemini":
        return GeminiLLM(config=config.gemini)
    elif provider_lower == "claude":
        return ClaudeLLM(config=config.claude)
    elif provider_lower == "mock":
        return MockLLM()
    else:
        raise ValueError(f"Unsupported LLM provider: {provider}")
