"""LLM backend interface and implementations for Kesoku AI Agent.

Provides an abstract base class BaseLLM and a concrete GeminiLLM implementation.
"""

import asyncio
import os
import re
from abc import ABC, abstractmethod
from collections.abc import Callable
from typing import Any

from google import genai
from google.genai import types
from pydantic import BaseModel, Field

from kesoku.config import ClaudeConfig, GeminiConfig, get_config
from kesoku.constants import (
    ROLE_ASSISTANT,
    ROLE_SYSTEM,
    ROLE_TOOL,
    ROLE_USER,
    TYPE_THOUGHT,
    TYPE_TOOL_CALL,
    TYPE_TOOL_RESULT,
)
from kesoku.db import Message
from kesoku.logger import setup_logger

logger = setup_logger(__name__)


class ToolCallRequest(BaseModel):
    """Represents a requested tool execution from the LLM."""

    name: str
    arguments: dict[str, Any]
    thought_signature: str | None = None
    tool_call_id: str | None = None



class LLMResponse(BaseModel):
    """Standardized response from any LLM provider."""

    content: str
    thought: str | None = None
    tool_calls: list[ToolCallRequest] = Field(default_factory=list)
    prompt_tokens: int | None = None  # Input tokens (context history, system prompt, tools schema)
    candidates_tokens: int | None = None  # Output tokens generated by the model (thoughts, text responses, tool calls)
    total_tokens: int | None = None  # Total tokens consumed in this call (prompt + candidates)
    raw_response: str | None = None  # Raw model response representation


def function_to_anthropic_tool(func: Callable) -> dict[str, Any]:
    """Convert a Python function with type hints and docstrings to an Anthropic tool schema.

    Args:
        func: The Python callable function to convert.

    Returns:
        A dict matching the Anthropic tool schema format.
    """
    import inspect
    sig = inspect.signature(func)

    # Get description from docstring
    doc = inspect.getdoc(func) or ""
    # Use the first line of docstring as the summary description
    description = doc.split("\n\n")[0] if doc else f"Run the {func.__name__} function"

    properties = {}
    required = []

    # Map python type annotation to JSON schema types
    type_map = {
        str: "string",
        int: "integer",
        float: "number",
        bool: "boolean",
        dict: "object",
        list: "array",
    }

    for param_name, param in sig.parameters.items():
        if param_name == "context":
            continue  # Skip context parameter which is framework internal

        # Determine type
        param_type = "string"  # default fallback
        annotation = param.annotation

        # Handle Optional or Union types (like str | None or typing.Optional)
        import typing
        origin = typing.get_origin(annotation)
        if origin is typing.Union or str(origin) == "<class 'union'>":
            args = typing.get_args(annotation)
            non_none_args = [a for a in args if a is not type(None)]
            if non_none_args:
                annotation = non_none_args[0]

        if annotation in type_map:
            param_type = type_map[annotation]

        # Handle default value and required list
        param_prop = {"type": param_type}

        # Search docstring for parameter description: "param_name: description"
        param_desc = f"The {param_name} argument"
        if doc:
            pattern = rf"(?:Args:|Parameters:).*?{param_name}\s*:\s*(.*?)(?:\n\s*\w+\s*:|\n\n|\Z)"
            match = re.search(pattern, doc, re.DOTALL | re.IGNORECASE)
            if match:
                param_desc = match.group(1).strip().replace("\n", " ")

        param_prop["description"] = param_desc
        properties[param_name] = param_prop

        if param.default is inspect.Parameter.empty:
            required.append(param_name)

    return {
        "name": func.__name__,
        "description": description,
        "input_schema": {
            "type": "object",
            "properties": properties,
            "required": required,
        },
    }


def _detect_image_mime_type(file_bytes: bytes, fallback_mime: str = "image/jpeg") -> str:
    """Detect image mime type from magic bytes.

    Returns:
        The detected mime_type string (e.g., 'image/png', 'image/jpeg').
    """
    if file_bytes.startswith(b"\x89PNG\r\n\x1a\n"):
        return "image/png"
    if file_bytes.startswith(b"\xff\xd8\xff"):
        return "image/jpeg"
    if file_bytes.startswith(b"GIF87a") or file_bytes.startswith(b"GIF89a"):
        return "image/gif"
    if file_bytes.startswith(b"RIFF") and len(file_bytes) >= 12 and file_bytes[8:12] == b"WEBP":
        return "image/webp"
    return fallback_mime


class BaseLLM(ABC):
    """Abstract base class defining the interface for LLM providers."""

    @abstractmethod
    async def generate(
        self,
        prompt: str | None = None,
        system_prompt: str | None = None,
        history: list[Message] | None = None,
        tools: list[Callable] | None = None,
    ) -> LLMResponse:
        """Generate a response from the LLM given prompt and context.

        Args:
            prompt: The latest user prompt string or None if continuation.
            system_prompt: Optional system instructions.
            history: Optional list of prior messages in the session.
            tools: Optional list of callable Python tool functions.

        Returns:
            An LLMResponse containing text and/or requested tool calls.
        """
        pass


class GeminiLLM(BaseLLM):
    """Google GenAI (Gemini) implementation of BaseLLM supporting API Key and Vertex AI."""

    def __init__(self, config: GeminiConfig | None = None) -> None:
        """Initialize the Gemini LLM client.

        Args:
            config: Configuration structure for Gemini backend.
        """
        if config is None:
            config = get_config().gemini
        self.config = config
        self.model_name = config.model_name
        logger.info(f"Using GeminiLLM backend ({self.model_name}).")

        try:
            if config.auth_mode == "vertex":
                logger.info(
                    f"Initializing Gemini client in Vertex AI mode "
                    f"(Project: {config.project_id}, Region: {config.location})"
                )
                self.client = genai.Client(
                    vertexai=True,
                    project=config.project_id,
                    location=config.location,
                )
            else:
                key = config.api_key or os.getenv("GEMINI_API_KEY")
                if not key:
                    logger.warning("GEMINI_API_KEY is not set. GeminiLLM calls may fail if not authenticated.")
                self.client = genai.Client(api_key=key)
        except ImportError:
            logger.error("google-genai package is not installed.")
            raise

    async def generate(
        self,
        prompt: str | None = None,
        system_prompt: str | None = None,
        history: list[Message] | None = None,
        tools: list[Callable] | None = None,
    ) -> LLMResponse:
        """Generate content using Google GenAI client."""
        contents: list[types.Content] = []
        if history:
            for msg in history:
                if msg.role == ROLE_SYSTEM:
                    if not system_prompt:
                        system_prompt = msg.content
                    elif msg != history[0]:
                        part = types.Part.from_text(text=f"[System Notification]\n{msg.content}")
                        if contents and contents[-1].role == "user":
                            contents[-1].parts.append(part)
                        else:
                            contents.append(types.Content(role="user", parts=[part]))
                    continue

                role = "user"
                parts = []

                if msg.role == ROLE_USER:
                    role = "user"
                    parts.append(types.Part.from_text(text=msg.content))
                    attachments = msg.metadata.get("attachments", [])
                    for att in attachments:
                        path = att.get("path")
                        mime_type = att.get("mime_type", "application/octet-stream")
                        if path and os.path.exists(path):  # noqa: ASYNC240
                            try:
                                with open(path, "rb") as f:  # noqa: ASYNC230
                                    file_bytes = f.read()
                                corrected_mime = mime_type
                                if mime_type.startswith("image/"):
                                    corrected_mime = _detect_image_mime_type(file_bytes, fallback_mime=mime_type)
                                parts.append(types.Part.from_bytes(data=file_bytes, mime_type=corrected_mime))
                                logger.info(f"Loaded native Gemini attachment part: {path} ({corrected_mime})")
                            except Exception as ex:
                                logger.error(f"Failed to load attachment {path} for Gemini: {ex}")
                elif msg.role == ROLE_ASSISTANT:
                    role = "model"
                    part = types.Part.from_text(text=msg.content)
                    if msg.type == TYPE_THOUGHT:
                        part.thought = True
                    parts.append(part)
                elif msg.role == ROLE_TOOL:
                    if msg.type == TYPE_TOOL_CALL:
                        role = "model"
                        tool_name = msg.metadata.get("tool_name", "unknown_tool")
                        args = msg.metadata.get("tool_arguments", {})
                        part = types.Part.from_function_call(name=tool_name, args=args)
                        ts_hex = msg.metadata.get("thought_signature")
                        if ts_hex:
                            part.thought_signature = bytes.fromhex(ts_hex)
                        parts.append(part)
                    elif msg.type == TYPE_TOOL_RESULT:
                        role = "tool"
                        tool_name = msg.metadata.get("tool_name", "unknown_tool")
                        if "tool_error" in msg.metadata:
                            res_dict = {"error": msg.metadata["tool_error"]}
                        else:
                            res_dict = {"result": msg.metadata.get("tool_result", msg.content)}
                        part = types.Part.from_function_response(name=tool_name, response=res_dict)
                        parts.append(part)

                if parts:
                    if contents and contents[-1].role == role:
                        contents[-1].parts.extend(parts)
                    else:
                        contents.append(types.Content(role=role, parts=parts))

        if prompt:
            part = types.Part.from_text(text=prompt)
            if contents and contents[-1].role == "user":
                contents[-1].parts.append(part)
            else:
                contents.append(types.Content(role="user", parts=[part]))

        config = types.GenerateContentConfig()
        if system_prompt:
            config.system_instruction = system_prompt
        if tools:
            config.tools = tools  # type: ignore
            config.automatic_function_calling = types.AutomaticFunctionCallingConfig(disable=True)
        if self.config.thinking_level is not None:
            config.thinking_config = types.ThinkingConfig(
                thinking_level=self.config.thinking_level,
                include_thoughts=True,
            )

        def _call() -> Any:
            if self.config.auth_mode == "vertex":
                client = genai.Client(
                    vertexai=True,
                    project=self.config.project_id,
                    location=self.config.location,
                )
            else:
                key = self.config.api_key or os.getenv("GEMINI_API_KEY")
                client = genai.Client(api_key=key)

            return client.models.generate_content(
                model=self.model_name,
                contents=contents,
                config=config,
            )

        try:
            res = await asyncio.to_thread(_call)
            tool_calls = []
            text_parts = []
            thought_parts = []

            if res.parts:
                for part in res.parts:
                    if isinstance(part.text, str):
                        if part.thought:
                            thought_parts.append(part.text)
                        else:
                            text_parts.append(part.text)
                    if part.function_call:
                        call = part.function_call
                        args_dict = dict(call.args) if call.args else {}
                        ts = part.thought_signature.hex() if part.thought_signature else None
                        tool_calls.append(ToolCallRequest(name=call.name, arguments=args_dict, thought_signature=ts))

            text_content = "".join(text_parts)
            thought_content = "".join(thought_parts) if thought_parts else None

            prompt_tokens = None
            candidates_tokens = None
            total_tokens = None
            if getattr(res, "usage_metadata", None):
                prompt_tokens = res.usage_metadata.prompt_token_count
                candidates_tokens = res.usage_metadata.candidates_token_count
                total_tokens = res.usage_metadata.total_token_count

            return LLMResponse(
                content=text_content,
                thought=thought_content,
                tool_calls=tool_calls,
                prompt_tokens=prompt_tokens,
                candidates_tokens=candidates_tokens,
                total_tokens=total_tokens,
            )

        except Exception as e:
            logger.error(f"GeminiLLM generation failed: {e}")
            raise


class ClaudeLLM(BaseLLM):
    """Anthropic Claude implementation of BaseLLM supporting Vertex AI."""

    def __init__(self, config: ClaudeConfig | None = None) -> None:
        """Initialize the Claude LLM client.

        Args:
            config: Configuration structure for Claude backend.
        """
        if config is None:
            config = get_config().claude
        self.config = config
        self.model_name = config.model_name
        logger.info(f"Using ClaudeLLM backend ({self.model_name}).")

        try:
            from anthropic import AnthropicVertex

            logger.info(
                f"Initializing Claude client in Vertex AI mode "
                f"(Project: {config.project_id}, Region: {config.location})"
            )
            self.client = AnthropicVertex(
                project_id=config.project_id,
                region=config.location,
            )
        except ImportError:
            logger.error("anthropic package is not installed.")
            raise

    async def generate(
        self,
        prompt: str | None = None,
        system_prompt: str | None = None,
        history: list[Message] | None = None,
        tools: list[Callable] | None = None,
    ) -> LLMResponse:
        """Generate content using Anthropic Vertex client."""
        messages = []

        anthropic_tools = []
        if tools:
            for t in tools:
                anthropic_tools.append(function_to_anthropic_tool(t))

        if history:
            merged_messages = []

            for msg in history:
                if msg.role == ROLE_SYSTEM:
                    if not system_prompt:
                        system_prompt = msg.content
                    elif msg != history[0]:
                        # Subsequent system messages as user message
                        block = {"type": "text", "text": f"[System Notification]\n{msg.content}"}
                        if merged_messages and merged_messages[-1]["role"] == "user":
                            merged_messages[-1]["content"].append(block)
                        else:
                            merged_messages.append({"role": "user", "content": [block]})
                    continue

                role = "user"
                blocks = []

                if msg.role == ROLE_USER:
                    role = "user"
                    blocks.append({"type": "text", "text": msg.content})
                    attachments = msg.metadata.get("attachments", [])
                    for att in attachments:
                        path = att.get("path")
                        mime_type = att.get("mime_type", "application/octet-stream")
                        if path and os.path.exists(path):  # noqa: ASYNC240
                            try:
                                import base64
                                with open(path, "rb") as f:  # noqa: ASYNC230
                                    file_bytes = f.read()
                                data_b64 = base64.b64encode(file_bytes).decode("utf-8")

                                if mime_type.startswith("image/"):
                                    corrected_mime = _detect_image_mime_type(file_bytes, fallback_mime=mime_type)
                                    blocks.append({
                                        "type": "image",
                                        "source": {
                                            "type": "base64",
                                            "media_type": corrected_mime,
                                            "data": data_b64,
                                        },
                                    })
                                    logger.info(f"Loaded native Claude image part: {path} ({corrected_mime})")
                                elif mime_type == "application/pdf":
                                    blocks.append({
                                        "type": "document",
                                        "source": {
                                            "type": "base64",
                                            "media_type": "application/pdf",
                                            "data": data_b64,
                                        },
                                    })
                                    logger.info(f"Loaded native Claude document part: {path} ({mime_type})")
                                else:
                                    logger.warning(f"Unsupported attachment type for Claude: {mime_type}")
                            except Exception as ex:
                                logger.error(f"Failed to load attachment {path} for Claude: {ex}")
                elif msg.role == ROLE_ASSISTANT:
                    role = "assistant"
                    if msg.type == TYPE_THOUGHT:
                        blocks.append({"type": "text", "text": f"<thought>\n{msg.content}\n</thought>"})
                    else:
                        blocks.append({"type": "text", "text": msg.content})
                elif msg.role == ROLE_TOOL:
                    if msg.type == TYPE_TOOL_CALL:
                        role = "assistant"
                        tool_name = msg.metadata.get("tool_name", "unknown_tool")
                        args = msg.metadata.get("tool_arguments", {})
                        tool_call_id = msg.metadata.get("tool_call_id") or msg.id
                        if not tool_call_id.startswith("toolu_"):
                            tool_call_id = f"toolu_{tool_call_id}"
                        blocks.append({
                            "type": "tool_use",
                            "id": tool_call_id,
                            "name": tool_name,
                            "input": args,
                        })
                    elif msg.type == TYPE_TOOL_RESULT:
                        role = "user"
                        tool_name = msg.metadata.get("tool_name", "unknown_tool")
                        if "tool_error" in msg.metadata:
                            res_str = f"Error: {msg.metadata['tool_error']}"
                            is_error = True
                        else:
                            res_str = msg.metadata.get("tool_result", msg.content)
                            is_error = False

                        parent_tc = next((m for m in history if m.id == msg.parent_id), None)
                        tool_call_id = None
                        if parent_tc:
                            tool_call_id = parent_tc.metadata.get("tool_call_id")
                        if not tool_call_id:
                            tool_call_id = msg.parent_id
                        if not tool_call_id.startswith("toolu_"):
                            tool_call_id = f"toolu_{tool_call_id}"

                        block = {
                            "type": "tool_result",
                            "tool_use_id": tool_call_id,
                            "content": res_str,
                        }
                        if is_error:
                            block["is_error"] = True
                        blocks.append(block)

                if blocks:
                    if merged_messages and merged_messages[-1]["role"] == role:
                        merged_messages[-1]["content"].extend(blocks)
                    else:
                        merged_messages.append({"role": role, "content": blocks})

            messages = merged_messages

        if prompt:
            block = {"type": "text", "text": prompt}
            if messages and messages[-1]["role"] == "user":
                messages[-1]["content"].append(block)
            else:
                messages.append({"role": "user", "content": [block]})

        if not messages:
            messages = [{"role": "user", "content": [{"type": "text", "text": "Hello"}]}]

        if messages[0]["role"] != "user":
            messages.insert(0, {"role": "user", "content": [{"type": "text", "text": "Hello"}]})

        final_messages = []
        for m in messages:
            if final_messages and final_messages[-1]["role"] == m["role"]:
                final_messages[-1]["content"].extend(m["content"])
            else:
                final_messages.append(m)

        def _call() -> Any:
            from anthropic import AnthropicVertex

            client = AnthropicVertex(
                project_id=self.config.project_id,
                region=self.config.location,
            )

            kwargs = {
                "model": self.model_name,
                "messages": final_messages,
                "max_tokens": 4096,
            }
            if system_prompt:
                kwargs["system"] = system_prompt
            if anthropic_tools:
                kwargs["tools"] = anthropic_tools

            return client.messages.create(**kwargs)

        try:
            res = await asyncio.to_thread(_call)
            tool_calls = []
            text_parts = []
            thought_parts = []

            if res.content:
                for block in res.content:
                    if block.type == "text":
                        text = block.text
                        thought_match = re.search(r"<thought>(.*?)</thought>", text, re.DOTALL)
                        if thought_match:
                            thought_parts.append(thought_match.group(1).strip())
                            text = re.sub(r"<thought>.*?</thought>", "", text, flags=re.DOTALL).strip()
                        text_parts.append(text)
                    elif block.type == "tool_use":
                        tool_calls.append(
                            ToolCallRequest(
                                name=block.name,
                                arguments=dict(block.input) if block.input else {},
                                thought_signature=None,
                                tool_call_id=block.id,
                            )
                        )

            text_content = "\n".join(text_parts).strip()
            thought_content = "\n".join(thought_parts).strip() if thought_parts else None

            prompt_tokens = None
            candidates_tokens = None
            total_tokens = None
            if getattr(res, "usage", None):
                prompt_tokens = res.usage.input_tokens
                candidates_tokens = res.usage.output_tokens
                total_tokens = prompt_tokens + candidates_tokens

            raw_json = None
            try:
                if "Mock" in type(res).__name__:
                    raw_json = str(res)
                elif hasattr(res, "to_json"):
                    val = res.to_json()
                    raw_json = val if isinstance(val, str) else str(val)
                elif hasattr(res, "model_dump_json"):
                    val = res.model_dump_json()
                    raw_json = val if isinstance(val, str) else str(val)
                else:
                    raw_json = str(res)
            except Exception as se:
                raw_json = f"Failed to serialize: {se}\nRaw: {repr(res)}"

            return LLMResponse(
                content=text_content,
                thought=thought_content,
                tool_calls=tool_calls,
                prompt_tokens=prompt_tokens,
                candidates_tokens=candidates_tokens,
                total_tokens=total_tokens,
                raw_response=raw_json,
            )
        except Exception as e:
            logger.error(f"ClaudeLLM generation failed: {e}")
            raise


class MockLLM(BaseLLM):
    """Mock LLM implementation for unit testing and local verification."""

    def __init__(
        self, mock_response: str = "Hello! I am Kesoku Agent.", mock_tools: list[ToolCallRequest] | None = None
    ) -> None:
        """Initialize MockLLM with canned responses."""
        self.mock_response = mock_response
        self.mock_tools = mock_tools or []

    async def generate(
        self,
        prompt: str | None = None,
        system_prompt: str | None = None,
        history: list[Message] | None = None,
        tools: list[Callable] | None = None,
    ) -> LLMResponse:
        """Return canned mock response."""
        logger.debug(f"MockLLM received prompt: {prompt}, history count: {len(history or [])}")
        prompt_str = prompt or (history[-1].content if history else "")
        if history and history[-1].role == "tool" and history[-1].type == "tool_result":
            return LLMResponse(content="The calculation result is 35.", tool_calls=[])
        if "calculate" in prompt_str.lower() or "+" in prompt_str:
            return LLMResponse(
                content="Let me calculate that.",
                tool_calls=[ToolCallRequest(name="calculator", arguments={"expression": "25 + 10"})],
            )
        return LLMResponse(content=self.mock_response, tool_calls=self.mock_tools)


def get_llm(provider: str | None = None) -> BaseLLM:
    """Get an LLM instance based on config or specified provider.

    Args:
        provider: Optional provider name ('gemini', 'claude', or 'mock'). If None, uses agent.llm from config.

    Returns:
        An instance of BaseLLM (GeminiLLM, ClaudeLLM, or MockLLM).

    Raises:
        ValueError: If an unsupported LLM provider is specified.
    """
    if provider is None:
        provider = get_config().agent.llm

    provider_lower = provider.lower()
    if provider_lower == "gemini":
        return GeminiLLM()
    elif provider_lower == "claude":
        return ClaudeLLM()
    elif provider_lower == "mock":
        return MockLLM()
    else:
        raise ValueError(f"Unsupported LLM provider: {provider}")
