"""System-wide constants for Kesoku AI Agent framework."""

# --- Message Roles ---
# Sent by the external human user.
ROLE_USER = "user"
# Sent by the Kesoku autonomous assistant (thoughts and responses).
ROLE_ASSISTANT = "assistant"
# Requested tool calls or resulting tool outputs.
ROLE_TOOL = "tool"
# Internal system instructions, error messages, or followup prompts.
ROLE_SYSTEM = "system"

# --- Message Types ---
# Standard textual conversation content.
TYPE_TEXT = "text"
# Internal reasoning or chain-of-thought generated by the assistant before executing tools.
TYPE_THOUGHT = "thought"
# A specific requested invocation of an external tool or skill.
TYPE_TOOL_CALL = "tool_call"
# The execution output or exception returned by an invoked tool.
TYPE_TOOL_RESULT = "tool_result"

# --- User Message Lifecycle Statuses ---
# Ingested user prompt awaiting pickup by an agent session worker.
STATUS_PENDING_AGENT = "pending_agent"
# User prompt currently actively being evaluated by an agent session worker.
STATUS_PROCESSING = "processing"
# User prompt successfully evaluated and answered by an agent session worker.
STATUS_PROCESSED = "processed"
# User prompt processing halted or pivoted due to a newer user thought interruption.
STATUS_INTERRUPTED = "interrupted"
# Message processing failed due to missing session or unrecoverable error.
STATUS_ERROR = "error"

# --- Assistant & Tool Message Lifecycle Statuses ---
# Outgoing assistant text response awaiting transmission by a chatbot adapter.
STATUS_PENDING = "pending"
# Successfully delivered final assistant text response on the external chat platform.
STATUS_COMPLETED = "completed"
# Successfully processed internal message (system instructions, thoughts, tool calls, tool outputs).
STATUS_RESPONDED = "responded"

# --- System Defaults ---
# Default defining instructions for the autonomous agent loop.
DEFAULT_SYSTEM_PROMPT = """You are Kesoku Agent, a helpful, highly capable autonomous AI assistant.
You can use available tools to calculate equations, search information, and answer user questions precisely.
"""
