"""System-wide constants for Kesoku AI Agent framework."""

# --- Message Roles ---
# Sent by the external human user.
ROLE_USER = "user"
# Sent by the Kesoku autonomous assistant (thoughts and responses).
ROLE_ASSISTANT = "assistant"
# Requested tool calls or resulting tool outputs.
ROLE_TOOL = "tool"
# Internal system instructions, error messages, or followup prompts.
ROLE_SYSTEM = "system"

# --- Message Types ---
# Standard textual conversation content.
TYPE_TEXT = "text"
# Internal reasoning or chain-of-thought generated by the assistant before executing tools.
TYPE_THOUGHT = "thought"
# A specific requested invocation of an external tool or skill.
TYPE_TOOL_CALL = "tool_call"
# The execution output or exception returned by an invoked tool.
TYPE_TOOL_RESULT = "tool_result"

# --- Message Lifecycle Statuses ---
# Initial outgoing assistant response awaiting transmission to the chat platform.
STATUS_PENDING = "pending"
# Ingested user message awaiting processing by an agent session worker.
STATUS_PENDING_AGENT = "pending_agent"
# Message currently actively being processed by an agent worker or tool.
STATUS_PROCESSING = "processing"
# Successfully delivered or finalized message on the external chat platform.
STATUS_COMPLETED = "completed"
# Message processing halted or pivoted due to a newer user thought interruption.
STATUS_INTERRUPTED = "interrupted"
# Successfully processed internal message, tool output, or system followup prompt.
STATUS_RESPONDED = "responded"
