"""System-wide constants and enums for Kesoku AI Agent framework."""

import datetime
from enum import StrEnum


class MessageRole(StrEnum):
    """Message roles within the Kesoku framework."""

    USER = "user"
    """Sent by the external human user."""
    ASSISTANT = "assistant"
    """Sent by the Kesoku autonomous assistant (thoughts and responses)."""
    TOOL = "tool"
    """Requested tool calls or resulting tool outputs."""
    SYSTEM = "system"
    """Internal system instructions, error messages, or followup prompts."""


class MessageType(StrEnum):
    """Message types within the Kesoku framework."""

    TEXT = "text"
    """Standard textual conversation content."""
    THOUGHT = "thought"
    """Internal reasoning or chain-of-thought generated by the assistant before executing tools."""
    TOOL_CALL = "tool_call"
    """A specific requested invocation of an external tool or skill."""
    TOOL_RESULT = "tool_result"
    """The execution output or exception returned by an invoked tool."""


class MessageStatus(StrEnum):
    """Message lifecycle statuses within the Kesoku framework."""

    # User message statuses
    PENDING_AGENT = "pending_agent"
    """Ingested user prompt awaiting pickup by an agent session worker."""
    PROCESSING = "processing"
    """User prompt currently actively being evaluated by an agent session worker."""
    PROCESSED = "processed"
    """User prompt successfully evaluated and answered by an agent session worker."""
    INTERRUPTED = "interrupted"
    """User prompt processing halted or pivoted due to a newer user thought interruption."""
    ERROR = "error"
    """Message processing failed due to missing session or unrecoverable error."""

    # Assistant & Tool message statuses
    PENDING = "pending"
    """Outgoing assistant text response awaiting transmission by a chatbot adapter."""
    DELIVERED = "delivered"
    """Successfully delivered final assistant text response on the external chat platform."""
    RESPONDED = "responded"
    """Successfully processed internal message (system instructions, thoughts, tool calls, tool outputs)."""


SYSTEM_START_TIME = datetime.datetime.now()


