"""Multimedia QA tools for Kesoku AI Agent using LLM multimodal capabilities."""

import logging
import mimetypes
import os

from kesoku.agent.llm import get_llm
from kesoku.agent.tools.registry import ToolContext, default_registry
from kesoku.constants import MessageRole, MessageType
from kesoku.db import Message
from kesoku.utils.async_fs import async_exists
from kesoku.utils.path import PathResolver

logger = logging.getLogger(__name__)


@default_registry.register
async def analyze_media(
    path: str,
    prompt: str = "Describe the content of this file in detail.",
    context: ToolContext | None = None,
) -> str:
    """Analyze a multimedia file (image, audio, video) by asking questions using an LLM.

    Args:
        path: Target path to the multimedia file (image, audio, video).
        prompt: Question or analysis prompt to execute against the file.
        context: Optional tool execution context.

    Returns:
        Analysis answer generated by the LLM.
    """
    if not context:
        return "Error: ToolContext is missing."

    resolved_path = None
    abs_path = PathResolver.resolve(path)
    if await async_exists(abs_path):
        resolved_path = abs_path
    elif context.session_workspace:
        staging_path = os.path.join(PathResolver.get_session_staging_dir(context.session_workspace), path)
        if await async_exists(staging_path):
            resolved_path = staging_path

    if not resolved_path or not await async_exists(resolved_path):
        return f"Error: Media file '{path}' does not exist."

    mime_type, _ = mimetypes.guess_type(resolved_path)
    if not mime_type:
        mime_type = "application/octet-stream"

    logger.info(f"Analyzing media file '{resolved_path}' ({mime_type}) with prompt: '{prompt}'")

    msg = Message(
        session_id=context.session_id,
        chatbot_id="system",
        channel_id="system",
        sender="User",
        role=MessageRole.USER,
        type=MessageType.TEXT,
        content=prompt,
        metadata={"attachments": [{"path": resolved_path, "mime_type": mime_type}]},
    )

    llm = (
        context.gateway.context.get_llm()
        if getattr(context, "gateway", None) and getattr(context.gateway, "context", None)
        else get_llm()
    )

    try:
        response = await llm.generate(history=[msg])
        return response.content
    except Exception as e:
        logger.error(f"Failed to analyze media file '{resolved_path}': {e}")
        return f"Error analyzing media file: {e}"
